### ISSUE TITLE
Don't alter images that don't need it (specifically re: resize)

### ISSUE THREAD

**Issue by melinath** [melinath/django-daguerre#73]
I don't know if this would be just a template tag feature or also in helpers, but. If an image is supposed to be resized and already is the size it will be, we should just copy the original file (or maybe just return the original file as the path?) The problem this would solve: jpeg artifacts on images that are already exactly the right size.

**Comment by harrislapiroff** [comment]
Probs in the helpers so this fix also captured the ajax feature, right? That's a thing, right? I can't remember.

**Comment by melinath** [comment]
Closing this one - we probably don't care, especially as images are getting larger and larger. If people need to avoid jpeg artifacts they should use png. And we shouldn't ever return the original image for security reasons - we should instead always be stripping exif data.
